#!/usr/bin/env ruby

require File.join(File.dirname(__FILE__), '../app/boot')

# # Setup
# ensure repeat all is off
Play::Player.app.repeat = false if Play::Player.app.repeat?

loop do
  songs = Play::Queue.songs
  current_song = Play::Player.now_playing
  unless current_song.pos == "0"
    current_song.pos.to_i.times do
      Play::Queue.remove_song_by_pos(0)
    end
  end
  # # Checks
  # ensure always atleast 1 song queued
  # ensure already played songs are cleared
  sleep 5
end
